name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Enable node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: TypeCheck
        run: pnpm tsc -b
      - name: Build
        run: pnpm nx affected --target=build --parallel=3
      - name: Test
        run: pnpm nx affected --target=test --parallel=2
      - name: Lint
        run: pnpm nx affected --target=lint --parallel=2
      - name: e2e
        run: pnpm nx affected --target=e2e --parallel=2
